spring:
  application:
    name: habit_tracker

  datasource:
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=tracker"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update